// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://zsfsdvgojgqxvqyuubyi.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzZnNkdmdvamdxeHZxeXV1YnlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM0NzAwMDQsImV4cCI6MjA0OTA0NjAwNH0.-LIBblD8UnC4NUhEX72u_WsEeKThdFueNfSS7uPb6EI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);